CREATE TABLE users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    email            VARCHAR(100)                            NOT NULL,
    first_name       VARCHAR(100),
    last_name        VARCHAR(100),
    password         VARCHAR(100),
    business_id      UUID                                    NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_business UNIQUE (business_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

CREATE UNIQUE INDEX idx_users__business_id ON users (business_id);

CREATE UNIQUE INDEX idx_users__email ON users (email);