CREATE TABLE password_reset
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    token      UUID                                    NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_password_reset PRIMARY KEY (id)
);

ALTER TABLE password_reset
    ADD CONSTRAINT uc_password_reset_token UNIQUE (token);

ALTER TABLE password_reset
    ADD CONSTRAINT FK_PASSWORD_RESET_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);