CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(60)                             NOT NULL,
    unit        VARCHAR(15),
    user_id     BIGINT                                  NOT NULL,
    business_id UUID                                    NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

ALTER TABLE product
    ADD CONSTRAINT uc_product__user_id__name__unit UNIQUE (user_id, name, unit);

ALTER TABLE product
    ADD CONSTRAINT uc_product_business UNIQUE (business_id);

CREATE UNIQUE INDEX idx_product_business_id ON product (business_id);

CREATE INDEX idx_product_name ON product (name);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);