CREATE TABLE customer
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_type      VARCHAR(31),
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at   TIMESTAMP WITHOUT TIME ZONE,
    email              VARCHAR(100),
    phone              VARCHAR(15),
    bank_acc_no        VARCHAR(26),
    notes              VARCHAR(255),
    user_id            BIGINT                                  NOT NULL,
    business_id        UUID                                    NOT NULL,
    company_name       VARCHAR(255),
    company_short_name VARCHAR(100),
    tax_id             VARCHAR(10),
    first_name         VARCHAR(100),
    last_name          VARCHAR(100),
    pesel              VARCHAR(11),
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

ALTER TABLE customer
    ADD CONSTRAINT uc_customer_business UNIQUE (business_id);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
