CREATE TABLE product_price
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    price            DECIMAL(19, 4)                          NOT NULL,
    valid_from       date                                    NOT NULL,
    product_id       BIGINT                                  NOT NULL,
    business_id      UUID                                    NOT NULL,
    CONSTRAINT pk_product_price PRIMARY KEY (id)
);

ALTER TABLE product_price
    ADD CONSTRAINT uc_product_price_business UNIQUE (business_id);

ALTER TABLE product_price
    ADD CONSTRAINT FK_PRODUCT_PRICE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

CREATE UNIQUE INDEX idx_product_price_business_id ON product_price (business_id);

