CREATE TABLE transaction
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    transaction_type VARCHAR(15),
    transaction_date TIMESTAMP WITHOUT TIME ZONE,
    payment_type     VARCHAR(15),
    payment_status   VARCHAR(20),
    user_id          BIGINT                                  NOT NULL,
    customer_id      BIGINT                                  NOT NULL,
    product_id       BIGINT                                  NOT NULL,
    business_id      UUID                                    NOT NULL,
    qty              DECIMAL(19, 2),
    price            DECIMAL(19, 2),
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);

ALTER TABLE transaction
    ADD CONSTRAINT uc_transaction_business UNIQUE (business_id);

CREATE UNIQUE INDEX idx_transaction_business_id ON transaction (business_id);

ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);

ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);